# E-Commerce SQL Project

#Q1. What is the total revenue?
SELECT SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales;

#Q2. What is the total quantity sold?
SELECT SUM(quantity) AS total_quantity
FROM ecommerce_sales;

#Q3. What is the total number of orders?
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce_sales;

#Q4. What is the revenue by category?
SELECT category,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY category
ORDER BY total_revenue DESC;

#Q5. Which region generated the highest revenue?
SELECT region,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY region
ORDER BY total_revenue DESC
LIMIT 1;

#Q6. What is the revenue by city?
SELECT city,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY city
ORDER BY total_revenue DESC;

#Q7. What is the revenue by product?
SELECT product_name,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY product_name
ORDER BY total_revenue DESC;

#Q8. Find the Top 10 products by revenue.
SELECT product_name,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 10;

#Q9. Find the Top 10 customers by revenue.
SELECT customer_name,
       SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY customer_name
ORDER BY total_revenue DESC
LIMIT 10;

#Q10. How many orders did each customer place?
SELECT customer_name,
       COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce_sales
GROUP BY customer_name
ORDER BY total_orders DESC;

#Q11. What is the quantity sold by region?
SELECT region,
       SUM(quantity) AS total_quantity
FROM ecommerce_sales
GROUP BY region
ORDER BY total_quantity DESC;

#Q12. What is the quantity sold by category?
SELECT category,
       SUM(quantity) AS total_quantity
FROM ecommerce_sales
GROUP BY category
ORDER BY total_quantity DESC;

#Q13. Calculate Average Order Value (AOV).
SELECT
    SUM(quantity * unit_price) /
    COUNT(DISTINCT order_id) AS average_order_value
FROM ecommerce_sales;

#Q14. Show revenue and quantity for each category.
SELECT
    category,
    SUM(quantity * unit_price) AS total_revenue,
    SUM(quantity) AS total_quantity
FROM ecommerce_sales
GROUP BY category
ORDER BY total_revenue DESC;

#Q15. Find monthly revenue.
SELECT
    MONTH(order_date) AS order_month,
    SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY MONTH(order_date)
ORDER BY order_month;

#Q16. Find customers whose revenue is greater than 10,000.
SELECT
    customer_name,
    SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY customer_name
HAVING total_revenue > 10000
ORDER BY total_revenue DESC;


#Q17. Create customer segments using CASE.
SELECT
    customer_name,
    SUM(quantity * unit_price) AS total_revenue,
    CASE
        WHEN SUM(quantity * unit_price) >= 10000 THEN 'High Value'
        WHEN SUM(quantity * unit_price) >= 5000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM ecommerce_sales
GROUP BY customer_name;


#Q18. Show the revenue generated by each sub-category.
SELECT
    sub_category,
    SUM(quantity * unit_price) AS total_revenue
FROM ecommerce_sales
GROUP BY sub_category
ORDER BY total_revenue DESC;

#Q19. Show individual order revenue.
SELECT
    order_id,
    customer_name,
    quantity,
    unit_price,
    quantity * unit_price AS revenue
FROM ecommerce_sales;

#Q20. Find the highest-priced product/order.
SELECT *
FROM ecommerce_sales
ORDER BY unit_price DESC
LIMIT 1;


-- END OF E-COMMERCE SALES ANALYTICS SQL


